excludes = [".envrc", ".gitignore", "LICENSE", "*.lock"]

[formatter.nix]
command = "nixfmt"
includes = ["*.nix"]


[formatter.taplo]
command = "taplo"
options = ["fmt"]
includes = ["*.toml"]


[formatter.prettier]
command = "prettier"
options = ["-w"]
includes = ["*.md"]
